services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: m123456
      POSTGRES_USER: makley
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

volumes:
  postgres-db-volume:
    external: false
